### ISSUE TITLE
How to use base-adapter-helper example:  ListView has many Different layouts

### ISSUE THREAD

**Issue by androidmalin** [JoanZapata/base-adapter-helper#41]
How to use base-adapter-helper example:  ListView has many Different layouts

**Comment by JoanZapata** [comment]
You can't use `QuickAdapter` for this, you have to create your own adapter overriding `getViewTypeCount()` and `getItemViewType()`. Then you can still use a different `BaseAdapterHelper` for each different item in the `convert` method.

**Comment by androidmalin** [comment]
Thanks very much
