### ISSUE TITLE
Skipped 60 frames!  The application may be doing too much work on its main thread

### ISSUE THREAD

**Issue by croccio** [JoanZapata/base-adapter-helper#49]
Skipped 60 frames!  The application may be doing too much work on its main thread.

How can i solve this problem? With a "manual custom adapter" i don't have this problem with same data

**Comment by JoanZapata** [comment]
Can you provide the code of your `QuickAdapter` / `BaseAdapter` ?

**Comment by JoanZapata** [comment]
Closed due to inactivity.
