### ISSUE TITLE
I found a problem in the use of your achievements, listview items inside will be chaos

### ISSUE THREAD

**Issue by KingHanWen** [JoanZapata/base-adapter-helper#50]

**Comment by KingHanWen** [comment]
Adapter update does not take effect
In the convert Method
adapter.notifyDataSetChanged();

**Comment by JoanZapata** [comment]
Please elaborate.

**Comment by KingHanWen** [comment]
Adapter data source changes
Call the method “notifyDataSetChanged”
Does not update Listview

**Comment by JoanZapata** [comment]
Please use `replaceAll()` on the adapter.
It will update the list and call `notifyDataSetChanged` for you.

**Comment by KingHanWen** [comment]
Thank you very much
