### ISSUE TITLE
Is that possible to support RecycleView?

### ISSUE THREAD

**Issue by KaiWangCanada** [JoanZapata/base-adapter-helper#58]
the library is awsome, but I'm using RecycleView right now, since it's so awsome. is that possible that the library could be revised to support RecycleView? thank you!

**Comment by KevinRoy** [comment]
expect support RecycleView！

**Comment by JoanZapata** [comment]
RecyclerView works in a very different way and won't be supported by base-adapter-helper. I think [this library](https://github.com/StanKocken/EfficientAdapter) already does the job.

**Comment by KevinRoy** [comment]
thanks
