### ISSUE TITLE
This lib just support Picasso ImageLoader?

### ISSUE THREAD

**Issue by eling13** [JoanZapata/base-adapter-helper#61]
If I want to use the picasso.Transformation,how can I do? Not support deliver the parameter like Transformation into the setImageUrl..API ??

**Comment by gzu-liyujiang** [comment]
建议作者把异步加载图片的那两个方法抽象出来，由其他开发者继承实现，自选图片加载框架。

**Comment by JoanZapata** [comment]
You can use `setImageBuilder`.

```
helper.setImageBuilder(R.id.image, 
    Picasso.with(context).load("...").transform(your_transformation_here));
```
